version: 2

formats: 
  - htmlzip
  - epub

python:
  version: "3.8.5"
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
    - method: setuptools
      path: another/package

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

